### PR TITLE
Should fix `E486: Pattern Not found: NerdTreeMirror` error

### PR DESCRIPTION
**Pull request by elizar**
---
This change is [Reviewable](https://reviewable.io/reviews/carlhuda/janus/665)

### CODE REVIEW

**Comment by kalbasit** [comment]
@elizar is this regarding #601 ? I was not able to confirm it myself. Do you want surround it with an `if exists('NERDTreeMirror')` instead?

**Comment by elizar** [comment]
@kalbasit Sure! Will push update in a bit...

**Comment by elizar** [comment]
@kalbasit I've put back the `:NERDTreeMirror` command and remove the space after `:NERDTreeToggle<CR>` instead which also fixes the #601 error. So no need to wrap it with a conditional statement I guess.

**Comment by elizar** [comment]
Although I'm not quite sure why the `space` causes a pattern related error on my end though.

**Comment by kalbasit** [comment]
Interesting, thank you for finding that out.

**Pull request merged**
